{% set name = "simplemseed" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f99b5b8ae62703d1b36308afaa5908396c6c3a8dd033bd4a6b804af955adec74

build:
  number: 0
  entry_points:
    - fdsnsourceid = simplemseed.fdsnsourceid:main
    - mseed3details = simplemseed.mseed3details:main
    - mseed3merge = simplemseed.mseed3merge:main
    - mseed2to3 = simplemseed.mseed2to3:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.9
    - hatchling >=1.21.0
    - pip
  run:
    - python >=3.9
    - crc32c
    - numpy <2.0dev0
    - jsonpointer
    - importlib-metadata

test:
  imports:
    - simplemseed
  commands:
    - python -c "from simplemseed import MSeed3Header, MSeed3Record, FDSNSourceId, readMSeed3Records;"
    - pip check
    - fdsnsourceid --help
    - mseed3details --help
    - mseed3merge --help
    - mseed2to3 --help
  requires:
    - pip

about:
  home: https://github.com/crotwell/simplemseed
  summary: miniseed3 in pure python
  license: LGPL-2.1-or-later
  license_file: LICENSE
  doc_url: https://simplemseed.readthedocs.io/en/latest/
  dev_url: https://github.com/crotwell/simplemseed

extra:
  recipe-maintainers:
    - megies
    - crotwell
